on: [pull_request, pull]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      users: actions/setup-go@v2
      with:
        go-version: ^1.14
        id: go
    - name: Test
      run: go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...
    - name: Test Coverage Report
      run: bash <(curl -s https://codecov.io/bash)